config/routes.rb
Rails.application.routes.draw do
  root "updates#index"

  resources :updates
  resources :one_on_ones
end

app/models/one_on_one.rb
class OneOnOne < ActiveRecord::Base
  validates_presence_of :student, :date
end

app/models/update.rb
class Update < ActiveRecord::Base
    default_scope { order('created_at') }
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/one_on_ones_controller.rb
class OneOnOnesController < ApplicationController
  before_action :set_one_on_one, only: [:show, :edit, :update, :destroy]

  # GET /one_on_ones
  # GET /one_on_ones.json
  def index
    @one_on_ones = OneOnOne.all
  end

  # GET /one_on_ones/1
  # GET /one_on_ones/1.json
  def show
  end

  # GET /one_on_ones/new
  def new
    @one_on_one = OneOnOne.new
  end

  # GET /one_on_ones/1/edit
  def edit
  end

  # POST /one_on_ones
  # POST /one_on_ones.json
  def create
    @one_on_one = OneOnOne.new(one_on_one_params)

    respond_to do |format|
      if @one_on_one.save

        @twilio = Twilio::REST::Client.new

        @twilio.messages.create(
          from: '+12062020609',
          to:   '+15169672755',
          body: "#{@one_on_one.student} just scheduled a one-on-one.\n
          http://www.nycda-voci.com/one_on_ones/#{@one_on_one.id}
          "
        )

        format.html { redirect_to @one_on_one, notice: 'One on one was successfully created.' }
        format.json { render :show, status: :created, location: @one_on_one }
      else
        format.html { render :new }
        format.json { render json: @one_on_one.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /one_on_ones/1
  # PATCH/PUT /one_on_ones/1.json
  def update
    respond_to do |format|
      if @one_on_one.update(one_on_one_params)
        format.html { redirect_to @one_on_one, notice: 'One on one was successfully updated.' }
        format.json { render :show, status: :ok, location: @one_on_one }
      else
        format.html { render :edit }
        format.json { render json: @one_on_one.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /one_on_ones/1
  # DELETE /one_on_ones/1.json
  def destroy
    @one_on_one.destroy
    respond_to do |format|
      format.html { redirect_to one_on_ones_url, notice: 'One on one was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_one_on_one
    @one_on_one = OneOnOne.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def one_on_one_params
    params.require(:one_on_one).permit(:student, :teacher, :topic, :date, :description)
  end
end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
  before_action :set_update, only: [:show, :edit, :update, :destroy]

  # GET /updates
  # GET /updates.json
  def index
    @updates = Update.all.reverse
  end

  # GET /updates/1
  # GET /updates/1.json
  def show
  end

  # GET /updates/new
  def new
    @update = Update.new
  end

  # GET /updates/1/edit
  def edit
  end

  # POST /updates
  # POST /updates.json
  def create
    require 'twilio-ruby'
    require 'net/http'
    require 'json'

    @update = Update.new(update_params)

    respond_to do |format|
      if @update.save


        format.html { redirect_to @update, notice: 'Update was successfully created.' }
        format.json { render :show, status: :created, location: @update }
      else
        format.html { render :new }
        format.json { render json: @update.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /updates/1
  # PATCH/PUT /updates/1.json
  def update
    respond_to do |format|
      if @update.update(update_params)
        format.html { redirect_to @update, notice: 'Update was successfully updated.' }
        format.json { render :show, status: :ok, location: @update }
      else
        format.html { render :edit }
        format.json { render json: @update.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /updates/1
  # DELETE /updates/1.json
  def destroy
    @update.destroy
    respond_to do |format|
      format.html { redirect_to updates_url, notice: 'Update was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_update
    @update = Update.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def update_params
    params.require(:update).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/one_on_ones_helper.rb
module OneOnOnesHelper
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/views/layouts/_navbar.html.erb
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Voci</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
          <li><%= link_to "sign out", sign_out_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "sign in", sign_in_path %></li>
          <%# <li><%= link_to "sign up", sign_up_path %1></li> %>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tag %>
  </head>

  <title>Voci</title>

  <body>
    <div class="container">
      <%= render "layouts/navbar" %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/one_on_ones/_form.html.erb
<%= form_for(@one_on_one) do |f| %>
  <% if @one_on_one.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@one_on_one.errors.count, "error") %> prohibited this one_on_one from being saved:</h2>

      <ul>
        <% @one_on_one.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-3">
      <div class="form-group">
        <%= f.label :student %><br>
        <%= f.text_field :student, autofocus: true, class: "form-control" %>
      </div>
    </div>

    <div class="col-md-3">
      <div class="form-group">
        <%= f.label :teacher %><br>
        <%= f.text_field :teacher, class: "form-control" %>
      </div>
    </div>

    <div class="col-md-3">
      <div class="form-group">
        <%= f.label :topic %><br>
        <%= f.text_field :topic, class: "form-control" %>
      </div>
    </div>

    <div class="col-md-3">
      <div class="field">
        <%= f.label :date, "When?" %><br>
        <%= f.text_field :date, class: "form-control" %>
      </div>
    </div>

  </div>

  <br />

  <div class="row">
    <div class="col-md-4">
    </div>

    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :description, "What's going on?" %><br>
        <%= f.text_area :description, class: "form-control", rows: 10 %>
      </div>
      <div class="actions">
        <%= f.submit "Go!", class: "btn btn-primary" %>
      </div>
    </div>

    <div class="col-md-4">
    </div>
  </div>

<% end %>

app/views/one_on_ones/edit.html.erb
<h1>Editing one_on_one</h1>

<%= render 'form' %>

<%= link_to 'Show', @one_on_one %> |
<%= link_to 'Back', one_on_ones_path %>

app/views/one_on_ones/index.html.erb
<h1>Listing One on Ones</h1>

<% if current_user %>
  <table>
    <thead>
      <tr>
        <th>Student</th>
        <th>Teacher</th>
        <th>Topic</th>
        <th>Time</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @one_on_ones.each do |one_on_one| %>
        <tr>
          <td><%= one_on_one.student %></td>
          <td><%= one_on_one.teacher %></td>
          <td><%= one_on_one.topic %></td>
          <td><%= one_on_one.date %></td>
          <td><%= one_on_one.description %></td>
          <td><%= link_to 'Show', one_on_one %></td>
          <td><%= link_to 'Edit', edit_one_on_one_path(one_on_one) %></td>
          <td><%= link_to 'Destroy', one_on_one, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New One on one', new_one_on_one_path %>
<% end %>

app/views/one_on_ones/new.html.erb
<h1>Schedule a One-on-One</h1>

<br />

<%= render 'form' %>

<%= link_to 'Back', one_on_ones_path %>

app/views/one_on_ones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @one_on_one.student %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @one_on_one.teacher %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @one_on_one.topic %>
</p>

<p>
  <strong>Time:</strong>
  <%= @one_on_one.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @one_on_one.description %>
</p>

<%= link_to 'Edit', edit_one_on_one_path(@one_on_one) %> |
<%= link_to 'Back', one_on_ones_path %>

app/views/updates/_form.html.erb
<%= form_for(@update) do |f| %>
  <% if @update.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@update.errors.count, "error") %> prohibited this update from being saved:</h2>

      <ul>
      <% @update.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, rows: 20, cols: 50, class: 'wysihtml5' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    $(".wysihtml5").each(function(i, elem) {
      $(elem).wysihtml5();
    });
  });
</script>

app/views/updates/edit.html.erb
<h1>Editing update</h1>

<% if current_user && current_user.admin %>
  <%= render 'form' %>
<% end %>

<%= link_to 'Show', @update %> |
<%= link_to 'Back', updates_path %>

app/views/updates/index.html.erb
<h1>Important Links</h1>

<a href="https://canvas.instructure.com/calendar#view_name=month&view_start=2016-09-12">
  Calendar <i class="glyphicon glyphicon-calendar"></i>
</a>

<br />

<a href="/one_on_ones/new">
  Schedule a 1-on-1 <i class="glyphicon glyphicon-comment"></i>
</a>


<h1>Updates</h1>

<%= link_to 'New Update', new_update_path %>

<br />
<br />

<ul>
  <% @updates.each do |update| %>
    <li><%= update.created_at.to_date %> | <%= link_to update.title, update %></li>
  <% end %>
</ul>

app/views/updates/new.html.erb
<h1>New update</h1>

<% if current_user && current_user.admin %>
  <%= render 'form' %>
<% end %>

<%= link_to 'Back', updates_path %>

app/views/updates/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @update.title %></h1>

<p>
  <%= raw(@update.body) %>
</p>


<%= link_to 'Edit', edit_update_path(@update) %> |
<%= link_to 'Back', updates_path %>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t('.title') %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t('.sign_in'), sign_in_path %>
    </div>
  <% end %>
</div>